name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: "yarn"

    - name: Install
      run: yarn install --frozen-lockfile --non-interactive

    - name: Lint
      run: yarn lint

    - name: Build App
      run: yarn build
      env:
        NODE_OPTIONS: --max_old_space_size=16384

    - name: Build Storybook
      run: yarn build-storybook
      env:
        NODE_OPTIONS: --max_old_space_size=16384

    - name: Test
      run: yarn test:coverage

    - name: Report Coverage
      if: always()
      uses:  davelosert/vitest-coverage-report-action@v1
