name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build App
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=16384

      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_OPTIONS: --max_old_space_size=16384

      - name: Test
        run: npm run test:coverage

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1
