name: deploy-dev

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    concurrency:
      group: ${{ github.ref }}-deploy
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: "yarn"

    - name: Install
      run: yarn install --frozen-lockfile --non-interactive

    - name: Build App
      run: yarn build
      env:
        NODE_OPTIONS: --max_old_space_size=16384

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # - uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_S3_BUCKET: BUCKET_NAME_HERE
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'us-east-1'
    #     SOURCE_DIR: 'dist'

  storybook:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-storybook
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: "yarn"

    - name: Install
      run: yarn install --frozen-lockfile --non-interactive

    - name: Build Storybook
      run: yarn build-storybook
      env:
        NODE_OPTIONS: --max_old_space_size=16384

    # - name: Deploy Storybook
    #   uses: chromaui/action@v1
    #   with:
    #     projectToken: TOKEN_HERE
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     storybookBuildDir: storybook-static
